<a href="https://colab.research.google.com/github/futureCodersSE/data-roles/blob/main/Data_jobs_jobsinkent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [119]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np

base_url = "https://jobsinkent.com/search?q=Data&pl=1" #&start=0
#jobsinkent_df = pd.DataFrame(data=[], columns = ["job_title", "company", "salary", "contract", "location","job_url"])
def get_html(url):
    #agent = {"User-Agent":"Mozilla/5.0"}
    page = requests.get(url) #, headers = agent

    soup = BeautifulSoup(page.content, 'html.parser') # 
    return soup

def clean_bloat(text):
  strip1 = text.strip("\n")
  strip2 = strip1.strip(" ")
  strip3 = strip2.strip("\n")
  return strip3

def find_jobs_iterate(url,job_limit):
  jobs_df = pd.DataFrame(data=[], columns = ["job_title", "company", "salary", "contract", "location","job_url"])
  site_html = get_html(url)
  results = site_html.find(class_="mt-2 lg:mt-0")

  job_cards = results.find_all(class_="flex mb-2 border-black-900 rounded-md border-x-4 sm:rounded-lg") #
  print("found jobs",len(job_cards))
  for job in job_cards[:job_limit]:

    job_title_url = job.find("a", class_="text-blue-700 visited:text-grey-200 hover:underline") #("p",class_="lg:text-2xl text-xl leading-6 font-bold hover:underline-offset-4")
    job_title = job_title_url.text
    job_url = job_title_url["href"]

    company_name = job.find(class_="mt-0 mb-2 max-w-2xl text-sm text-black").text
    info_list = job.find_all(class_="col-span-12")# truncate mt-1 max-w-2xl text-sm text-black flex items-center")
    salary = clean_bloat(info_list[0].text)
    contract = clean_bloat(info_list[1].text)
    location = clean_bloat(info_list[2].text)


    new_row = {"job_title":job_title, "company":company_name, "salary":salary, "contract":contract, "location":location,"job_url":job_url}
    jobs_df = jobs_df.append(new_row,ignore_index = True)
  display(jobs_df)
  return jobs_df

def return_jobs_pages(input_str):
  
  p_j = input_str.split("of")
  jobs_per_page = int(p_j[0].split("to")[1])
  total_jobs = int(p_j[1].split("Jobs")[0])
  
  total_pages = int(np.ceil(total_jobs/jobs_per_page))

  return total_jobs, jobs_per_page, total_pages

In [120]:
def main_scrape(url):
  jobsinkent_df = pd.DataFrame(data=[], columns = ["job_title", "company", "salary", "contract", "location","job_url"])
  ##construct_url = url+ "&page=" + page

  site_html = get_html(url)

  results = site_html.find("p", class_="text-sm text-gray-700 leading-5")
  showing = results.text


  total_jobs, jobs_per_page, total_pages = return_jobs_pages(showing)

  for page_no in range(1,total_pages+1):
    print("page_no ",page_no)
    if page_no == total_pages:
      jobs_limit = total_jobs%jobs_per_page
      print("jobs_limit ", jobs_limit)
    else:
      jobs_limit = jobs_per_page
      print("jobs_limit ", jobs_limit)

    construct_url = url + "&page=" + str(page_no)
    new_df = find_jobs_iterate(construct_url, jobs_limit)
    jobsinkent_df = jobsinkent_df.append(new_df, ignore_index=True)
  
  
  return jobsinkent_df
  

jobsinkent_df = main_scrape("https://jobsinkent.com/search?q=Data&pl=1")

page_no  1
jobs_limit  20
found jobs 40

,job_title,company,salary,contract,location,job_url
0,Immediate Start - Data Entry,Huntress,£11.00 - £11.63 per hour,"temporary,full-time","Ashford, Kent",https://jobsinkent.com/job/2389911
1,HE Data Quality & Exams Officer,North Kent College,"£12,810 pro-rata (£21,000 full time equivalent)","permanent,part-time","Tonbridge, Kent",https://jobsinkent.com/job/2423371
2,"Senior Azure Specialists WANTED - Native, Data...",Jump IT Recruitment Solutions Limited,£65K-£90K+Bens+Opportunity+Equity,"permanent,full-time",Work from home,https://jobsinkent.com/job/2145576
3,Data Analyst,Hays Specialist Recruitment Ltd,£45000.00 - £50000.00 per annum,"permanent,full-time","Dartford, Kent",https://jobsinkent.com/job/2145570
4,Senior Data Governance Manager,MW Appointments,£90000 - £110000 per annum + + package,"permanent,full-time","City of London, Greater London",https://jobsinkent.com/job/2053074
5,Azure Data Engineer,Pearson Whiffin Recruitment,£50000 - £60000 per annum,"permanent,full-time","Central London, Greater London",https://jobsinkent.com/job/2263413
6,Senior Data Analyst,Clarion Housing Group Ltd,£43264 - £59488 per annum,"permanent,full-time","Central London, Greater London",https://jobsinkent.com/job/2423530
7,Junior Data Analyst - MS SQL & Excel,Pearson Whiffin Recruitment,£22000 - £27500 per annum + Excellent Benefits,"permanent,full-time","Dover, Kent",https://jobsinkent.com/job/2052907
8,Data Protection & Governance Manager,Atlas Recruitment Group,£50000 - £55000 per annum + Bonus,"permanent,full-time","Hastings, Sussex",https://jobsinkent.com/job/2261948
9,"Data Scientist - AI, Python, Machine Learning,...",Jump IT Recruitment Solutions Limited,£35K-£90K+Bens+,"permanent,full-time",Work from home,https://jobsinkent.com/job/2261649
10,Financial Data Entry,Huntress,Negotiable,"temporary,full-time","West Malling, Kent",https://jobsinkent.com/job/2180856
11,Data Lead (Digital Marketing),Recruitment Solutions Folkestone Ltd,"£30-40,000 dep on exp","permanent,full-time","Ashford, Kent",https://jobsinkent.com/job/2277249
12,Data Analyst,MW Appointments,Up to £35000.00 per annum,"permanent,full-time","City of London, Greater London",https://jobsinkent.com/job/2142849
13,Data Entry Sage,Recruitment Solutions Folkestone Ltd,£9.50 per hour x 37 hours per week,"temporary,full-time","Folkestone, Kent",https://jobsinkent.com/job/2422759
14,Finance Data & Systems Lead,Hays Specialist Recruitment Ltd,"£60000.00 - £65000.00 per annum + parking, fl...","permanent,full-time",South West London,https://jobsinkent.com/job/2309432
15,Lecturer/Senior Lecturer in Biological Data Sc...,Canterbury Christ Church University,"£31,342- £45,954","permanent,full-time","Canterbury, Kent",https://jobsinkent.com/job/2422784
16,Data Analyst - Apprentice,Clarion Housing Group Ltd,Up to £25000 per annum + excellent benefits,"contract,full-time","Central London, Greater London",https://jobsinkent.com/job/2421388
17,Data Analyst,Clarion Housing Group Ltd,£31889 - £44286 per annum + excellent benefits,"temporary,full-time","Central London, Greater London",https://jobsinkent.com/job/2421387
18,"Data Analyst - Perm, FTC & Apprentice options",Clarion Housing Group Ltd,£31889 - £44286 per annum + excellent benefits,"permanent,full-time","Central London, Greater London",https://jobsinkent.com/job/2421383
19,Data Analyst,Commercial Services Interim & Executive Search,£41216 - £47199 per annum,"permanent,full-time","West Malling, Kent",https://jobsinkent.com/job/2423341

page_no  2
jobs_limit  20
found jobs 40

,job_title,company,salary,contract,location,job_url
0,Senior SQL Database Developer,Hays Specialist Recruitment Ltd,£55000.00 - £70000.00 per annum,"permanent,full-time","Sevenoaks, Kent",https://jobsinkent.com/job/2341211
1,Digital Analyst/ Data Visualisation Executive,Recruitment Solutions South East Ltd,£30-35000 + benefits; hybrid/remote,"permanent,full-time","Tunbridge Wells, Kent",https://jobsinkent.com/job/2422937
2,Data Entry Clerk,Connect2Staff,Up to £10 per hour,"temporary,full-time","Kings Hill, Kent",https://jobsinkent.com/job/2387643
3,Data Analyst / Quality Analyst,Pearson Whiffin Recruitment,"£35,000 - £45,000 per annum + Benefits","permanent,full-time","Sevenoaks, Kent",https://jobsinkent.com/job/2134054
4,Senior SQL Database Developer,Hays Specialist Recruitment Ltd,£55000.00 - £70000.00 per annum,"permanent,full-time","Tonbridge, Kent",https://jobsinkent.com/job/2381871
5,Marketing Data Administrator,Pearson Whiffin Recruitment,£20000 - £23000 per annum,"permanent,full-time","Sittingbourne, Kent",https://jobsinkent.com/job/2338739
6,Senior SQL Database Developer,Hays Specialist Recruitment Ltd,£70000.00 - £85000.00 per annum,"permanent,full-time","Westerham, Kent",https://jobsinkent.com/job/2419717
7,Immediate Start - Data Entry Administrator,Huntress,Up to £11 per hour,"temporary,full-time","Folkestone, Kent",https://jobsinkent.com/job/2252974
8,Immediate Start - Data Entry Administrator,Huntress,Up to £11 per hour,"temporary,full-time","Canterbury, Kent",https://jobsinkent.com/job/2252973
9,Junior Data Analyst - Office based,Pearson Whiffin Recruitment,£22000 - £28000 per annum,"permanent,full-time","West Malling, Kent",https://jobsinkent.com/job/2332912
10,Immediate Start - Data Entry,Huntress,Up to £11 per hour,"temporary,full-time","Ashford, Kent",https://jobsinkent.com/job/2251154
11,Data & M.I. Business Partner (Insurance),MW Appointments,Negotiable,"permanent,full-time","City of London, Greater London",https://jobsinkent.com/job/2049769
12,Data and Business Services Assistant,Barker Munro Recruitment Limited,"£20,000 - 30,000","permanent,full-time","Tunbridge Wells, Kent",https://jobsinkent.com/job/2133378
13,Graduate Data Analyst,Huntress,Up to £23000 per annum,"permanent,full-time","Tenterden, Kent",https://jobsinkent.com/job/2422248
14,Immediate Start - Data Entry,Huntress,Up to £20000 per annum,"temporary,full-time","Chatham, Kent",https://jobsinkent.com/job/2132885
15,Data Entry Clerk (finance),Connect2Staff,£8.91 - £9.00 per hour,"temporary,full-time","Aylesford, Tonbridge and Malling, Kent",https://jobsinkent.com/job/2132825
16,Data Entry Clerk,Connect2Staff,Up to £10 per hour,"temporary,full-time","West Malling, Kent",https://jobsinkent.com/job/2164411
17,Junior Data Analyst - SQL - Excel - VBA - Remo...,Pearson Whiffin Recruitment,£20000 - £28000 per annum,"permanent,full-time","Central London, Greater London",https://jobsinkent.com/job/2082056
18,Data Analyst,Pearson Whiffin Recruitment,£25000 - £30000 per annum + DOE,"permanent,full-time","Gillingham, Kent",https://jobsinkent.com/job/2132332
19,Temporary Data Entry Clerk,Connect2Staff,Up to £10 per hour,"temporary,full-time","Kings Hill, Kent",https://jobsinkent.com/job/2376533

page_no  3
jobs_limit  19
found jobs 39

,job_title,company,salary,contract,location,job_url
0,Data Entry Administrator,Huntress,Up to £10 per hour,"temporary,full-time","Gravesend, Kent",https://jobsinkent.com/job/2048219
1,Invoice Clerk / Data Entry,Huntress,Up to £9.80 per hour + Holiday pay + Free par...,"temporary,full-time","Dartford, Kent",https://jobsinkent.com/job/2047926
2,Database Administrator,Pearson Whiffin Recruitment,£20000 - £23000 per annum,"permanent,full-time","Sittingbourne, Kent",https://jobsinkent.com/job/2282433
3,Data Analyst - Global Insurance Markets,MW Appointments,Negotiable,"permanent,full-time","City of London, Greater London",https://jobsinkent.com/job/2422053
4,Data Analyst,Pearson Whiffin Recruitment,£23000 - £28000 per annum + DOE,"permanent,full-time","West Malling, Kent",https://jobsinkent.com/job/2331144
5,Data Cable Engineer - City of London,PW Construction,Negotiable,"temporary,full-time","City of London, Greater London",https://jobsinkent.com/job/2421623
6,Data Engineering Consultant,Recruitment Solutions,depending on experience,"permanent,full-time","Sevenoaks, Kent",https://jobsinkent.com/job/2421607
7,Azure Data Engineer,Pearson Whiffin Recruitment,£55000 - £60000 per annum,"permanent,full-time","Central London, Greater London",https://jobsinkent.com/job/2362033
8,"BI, Data & Performance Manager (Healthcare)",Commercial Services Trading Ltd,£52000 - £55000 per annum + (Pro Rata),"contract,part-time","Royal Tunbridge Wells, Kent",https://jobsinkent.com/job/2064801
9,Data Administrator,Manpower - Ashford,£10.00ph,"permanent,full-time/part-time","Tunbridge Wells, Kent",https://jobsinkent.com/job/1932171
10,Data Assistant / Analyst (with marketing),KHR - Recruitment Specialists,+ Benefits,"permanent,full-time","Sevenoaks, Kent",https://jobsinkent.com/job/2421290
11,Temporary Data Entry Clerk,Commercial Services Trading Ltd,£8.91 - £9.00 per hour,"temporary,full-time","Aylesford, Tonbridge and Malling, Kent",https://jobsinkent.com/job/2063952
12,Senior SQL Database Developer,Hays Specialist Recruitment Ltd,£70000.00 - £85000.00 per annum,"permanent,full-time","Sevenoaks, Kent",https://jobsinkent.com/job/2392506
13,Immediate Start Data-Entry,Huntress,£18000 - £20000 per annum,"temporary,full-time","West Malling, Kent",https://jobsinkent.com/job/2189560
14,"Pre-Sales Consultant - SQL, SaaS, Data - Hybri...",Jump IT Recruitment Solutions Limited,To £48K+Bens+Opportunity,"permanent,full-time",Kent,https://jobsinkent.com/job/2356058
15,Invoice Data Entry Clerk,Connect2Staff,£9.50 - £10 per hour,"contract,full-time","Aylesford, Tonbridge and Malling, Kent",https://jobsinkent.com/job/2421116
16,Data cable Engineer - Fulham ASAP,PW Construction,Negotiable,"permanent,full-time","Fulham, Greater London",https://jobsinkent.com/job/2313664
17,Data Administrator,Hays Specialist Recruitment,Up to £23500.00 per annum,"permanent,full-time","Slough, Berkshire",https://jobsinkent.com/job/2116836
18,Dispatch/Data Entry Administrator,Pearson Whiffin Recruitment,£20000 - £22000 per annum + great benefits,"permanent,full-time","Sittingbourne, Kent",https://jobsinkent.com/job/2044095

In [121]:
display(jobsinkent_df)
jobsinkent_df.to_excel("jobsinkent_df.xlsx")

,job_title,company,salary,contract,location,job_url
0,Immediate Start - Data Entry,Huntress,£11.00 - £11.63 per hour,"temporary,full-time","Ashford, Kent",https://jobsinkent.com/job/2389911
1,HE Data Quality & Exams Officer,North Kent College,"£12,810 pro-rata (£21,000 full time equivalent)","permanent,part-time","Tonbridge, Kent",https://jobsinkent.com/job/2423371
2,"Senior Azure Specialists WANTED - Native, Data...",Jump IT Recruitment Solutions Limited,£65K-£90K+Bens+Opportunity+Equity,"permanent,full-time",Work from home,https://jobsinkent.com/job/2145576
3,Data Analyst,Hays Specialist Recruitment Ltd,£45000.00 - £50000.00 per annum,"permanent,full-time","Dartford, Kent",https://jobsinkent.com/job/2145570
4,Senior Data Governance Manager,MW Appointments,£90000 - £110000 per annum + + package,"permanent,full-time","City of London, Greater London",https://jobsinkent.com/job/2053074
5,Azure Data Engineer,Pearson Whiffin Recruitment,£50000 - £60000 per annum,"permanent,full-time","Central London, Greater London",https://jobsinkent.com/job/2263413
6,Senior Data Analyst,Clarion Housing Group Ltd,£43264 - £59488 per annum,"permanent,full-time","Central London, Greater London",https://jobsinkent.com/job/2423530
7,Junior Data Analyst - MS SQL & Excel,Pearson Whiffin Recruitment,£22000 - £27500 per annum + Excellent Benefits,"permanent,full-time","Dover, Kent",https://jobsinkent.com/job/2052907
8,Data Protection & Governance Manager,Atlas Recruitment Group,£50000 - £55000 per annum + Bonus,"permanent,full-time","Hastings, Sussex",https://jobsinkent.com/job/2261948
9,"Data Scientist - AI, Python, Machine Learning,...",Jump IT Recruitment Solutions Limited,£35K-£90K+Bens+,"permanent,full-time",Work from home,https://jobsinkent.com/job/2261649
10,Financial Data Entry,Huntress,Negotiable,"temporary,full-time","West Malling, Kent",https://jobsinkent.com/job/2180856
11,Data Lead (Digital Marketing),Recruitment Solutions Folkestone Ltd,"£30-40,000 dep on exp","permanent,full-time","Ashford, Kent",https://jobsinkent.com/job/2277249
12,Data Analyst,MW Appointments,Up to £35000.00 per annum,"permanent,full-time","City of London, Greater London",https://jobsinkent.com/job/2142849
13,Data Entry Sage,Recruitment Solutions Folkestone Ltd,£9.50 per hour x 37 hours per week,"temporary,full-time","Folkestone, Kent",https://jobsinkent.com/job/2422759
14,Finance Data & Systems Lead,Hays Specialist Recruitment Ltd,"£60000.00 - £65000.00 per annum + parking, fl...","permanent,full-time",South West London,https://jobsinkent.com/job/2309432
15,Lecturer/Senior Lecturer in Biological Data Sc...,Canterbury Christ Church University,"£31,342- £45,954","permanent,full-time","Canterbury, Kent",https://jobsinkent.com/job/2422784
16,Data Analyst - Apprentice,Clarion Housing Group Ltd,Up to £25000 per annum + excellent benefits,"contract,full-time","Central London, Greater London",https://jobsinkent.com/job/2421388
17,Data Analyst,Clarion Housing Group Ltd,£31889 - £44286 per annum + excellent benefits,"temporary,full-time","Central London, Greater London",https://jobsinkent.com/job/2421387
18,"Data Analyst - Perm, FTC & Apprentice options",Clarion Housing Group Ltd,£31889 - £44286 per annum + excellent benefits,"permanent,full-time","Central London, Greater London",https://jobsinkent.com/job/2421383
19,Data Analyst,Commercial Services Interim & Executive Search,£41216 - £47199 per annum,"permanent,full-time","West Malling, Kent",https://jobsinkent.com/job/2423341
20,Senior SQL Database Developer,Hays Specialist Recruitment Ltd,£55000.00 - £70000.00 per annum,"permanent,full-time","Sevenoaks, Kent",https://jobsinkent.com/job/2341211
21,Digital Analyst/ Data Visualisation Executive,Recruitment Solutions South East Ltd,£30-35000 + benefits; hybrid/remote,"permanent,full-time","Tunbridge Wells, Kent",https://jobsinkent.com/job/2422937
22,Data Entry Clerk,Connect2Staff,Up to £10 per hour,"temporary,full-time","Kings Hill, Kent",https://jobsinkent.com/job/2387643
23,Data Analyst / Quality Analyst,Pearson Whiffin Recruitment,"£35,000 - £45,000 per annum + Benefits","permanent,full-time","Sevenoaks, Kent",https://jobsinkent.com/job/2134054
24,Senior SQL Database Developer,Hays Specialist Recruitment Ltd,£55000.00 - £70000.00 per annum,"permanent,full-time","Tonbridge, Kent",https://jobsinkent.com/job/2381871
25,Marketing Data Administrator,Pearson Whiffin Recruitment,£20000 - £23000 per annum,"permanent,full-time","Sittingbourne, Kent",https://jobsinkent.com/job/2338739
26,Senior SQL Database Developer,Hays Specialist Recruitment Ltd,£70000.00 - £85000.00 per annum,"permanent,full-time","Westerham, Kent",https://jobsinkent.com/job/2419717
27,Immediate Start - Data Entry Administrator,Huntress,Up to £11 per hour,"temporary,full-time","Folkestone, Kent",https://jobsinkent.com/job/2252974
28,Immediate Start - Data Entry Administrator,Huntress,Up to £11 per hour,"temporary,full-time","Canterbury, Kent",https://jobsinkent.com/job/2252973
29,Junior Data Analyst - Office based,Pearson Whiffin Recruitment,£22000 - £28000 per annum,"permanent,full-time","West Malling, Kent",https://jobsinkent.com/job/2332912
30,Immediate Start - Data Entry,Huntress,Up to £11 per hour,"temporary,full-time","Ashford, Kent",https://jobsinkent.com/job/2251154
31,Data & M.I. Business Partner (Insurance),MW Appointments,Negotiable,"permanent,full-time","City of London, Greater London",https://jobsinkent.com/job/2049769
32,Data and Business Services Assistant,Barker Munro Recruitment Limited,"£20,000 - 30,000","permanent,full-time","Tunbridge Wells, Kent",https://jobsinkent.com/job/2133378
33,Graduate Data Analyst,Huntress,Up to £23000 per annum,"permanent,full-time","Tenterden, Kent",https://jobsinkent.com/job/2422248
34,Immediate Start - Data Entry,Huntress,Up to £20000 per annum,"temporary,full-time","Chatham, Kent",https://jobsinkent.com/job/2132885
35,Data Entry Clerk (finance),Connect2Staff,£8.91 - £9.00 per hour,"temporary,full-time","Aylesford, Tonbridge and Malling, Kent",https://jobsinkent.com/job/2132825
36,Data Entry Clerk,Connect2Staff,Up to £10 per hour,"temporary,full-time","West Malling, Kent",https://jobsinkent.com/job/2164411
37,Junior Data Analyst - SQL - Excel - VBA - Remo...,Pearson Whiffin Recruitment,£20000 - £28000 per annum,"permanent,full-time","Central London, Greater London",https://jobsinkent.com/job/2082056
38,Data Analyst,Pearson Whiffin Recruitment,£25000 - £30000 per annum + DOE,"permanent,full-time","Gillingham, Kent",https://jobsinkent.com/job/2132332
39,Temporary Data Entry Clerk,Connect2Staff,Up to £10 per hour,"temporary,full-time","Kings Hill, Kent",https://jobsinkent.com/job/2376533
40,Data Entry Administrator,Huntress,Up to £10 per hour,"temporary,full-time","Gravesend, Kent",https://jobsinkent.com/job/2048219
41,Invoice Clerk / Data Entry,Huntress,Up to £9.80 per hour + Holiday pay + Free par...,"temporary,full-time","Dartford, Kent",https://jobsinkent.com/job/2047926
42,Database Administrator,Pearson Whiffin Recruitment,£20000 - £23000 per annum,"permanent,full-time","Sittingbourne, Kent",https://jobsinkent.com/job/2282433
43,Data Analyst - Global Insurance Markets,MW Appointments,Negotiable,"permanent,full-time","City of London, Greater London",https://jobsinkent.com/job/2422053
44,Data Analyst,Pearson Whiffin Recruitment,£23000 - £28000 per annum + DOE,"permanent,full-time","West Malling, Kent",https://jobsinkent.com/job/2331144
45,Data Cable Engineer - City of London,PW Construction,Negotiable,"temporary,full-time","City of London, Greater London",https://jobsinkent.com/job/2421623
46,Data Engineering Consultant,Recruitment Solutions,depending on experience,"permanent,full-time","Sevenoaks, Kent",https://jobsinkent.com/job/2421607
47,Azure Data Engineer,Pearson Whiffin Recruitment,£55000 - £60000 per annum,"permanent,full-time","Central London, Greater London",https://jobsinkent.com/job/2362033
48,"BI, Data & Performance Manager (Healthcare)",Commercial Services Trading Ltd,£52000 - £55000 per annum + (Pro Rata),"contract,part-time","Royal Tunbridge Wells, Kent",https://jobsinkent.com/job/2064801
49,Data Administrator,Manpower - Ashford,£10.00ph,"permanent,full-time/part-time","Tunbridge Wells, Kent",https://jobsinkent.com/job/1932171
50,Data Assistant / Analyst (with marketing),KHR - Recruitment Specialists,+ Benefits,"permanent,full-time","Sevenoaks, Kent",https://jobsinkent.com/job/2421290
51,Temporary Data Entry Clerk,Commercial Services Trading Ltd,£8.91 - £9.00 per hour,"temporary,full-time","Aylesford, Tonbridge and Malling, Kent",https://jobsinkent.com/job/2063952
52,Senior SQL Database Developer,Hays Specialist Recruitment Ltd,£70000.00 - £85000.00 per annum,"permanent,full-time","Sevenoaks, Kent",https://jobsinkent.com/job/2392506
53,Immediate Start Data-Entry,Huntress,£18000 - £20000 per annum,"temporary,full-time","West Malling, Kent",https://jobsinkent.com/job/2189560
54,"Pre-Sales Consultant - SQL, SaaS, Data - Hybri...",Jump IT Recruitment Solutions Limited,To £48K+Bens+Opportunity,"permanent,full-time",Kent,https://jobsinkent.com/job/2356058
55,Invoice Data Entry Clerk,Connect2Staff,£9.50 - £10 per hour,"contract,full-time","Aylesford, Tonbridge and Malling, Kent",https://jobsinkent.com/job/2421116
56,Data cable Engineer - Fulham ASAP,PW Construction,Negotiable,"permanent,full-time","Fulham, Greater London",https://jobsinkent.com/job/2313664
57,Data Administrator,Hays Specialist Recruitment,Up to £23500.00 per annum,"permanent,full-time","Slough, Berkshire",https://jobsinkent.com/job/2116836
58,Dispatch/Data Entry Administrator,Pearson Whiffin Recruitment,£20000 - £22000 per annum + great benefits,"permanent,full-time","Sittingbourne, Kent",https://jobsinkent.com/job/2044095